CREATE TABLE SMITH(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20),
    AGE INT,
    EMAIL VARCHAR(100)
);

INSERT INTO SMITH(NAME, AGE, EMAIL) VALUES('John', 25, 'john@petismithing.hu');
INSERT INTO SMITH(NAME, AGE, EMAIL) VALUES('Jane', 23, 'jane@petismithing.hu');
INSERT INTO SMITH(NAME, AGE, EMAIL) VALUES('Jack', 27, 'jack@petismithing.hu');
INSERT INTO SMITH(NAME, AGE, EMAIL) VALUES('Jill', 22, 'jill@petismithing.hu');


CREATE TABLE SMITH_WORK
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    SMITH_ID BIGINT,
    WORK BIGINT
);